[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  VITE_API_URL = "https://strategylab-backend-production.up.railway.app"

[[redirects]]
  from = "/api/*"
  to = "https://strategylab-backend-production.up.railway.app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
